### ISSUE TITLE
Serilog not sending logs to datadog via .Net 4.5.2

### ISSUE THREAD

**Issue by rdcm** [DataDog/serilog-sinks-datadog-logs#27] opened 2019-02-08 15:47 UTC
Configure logging:

```
            var key = config[DataDogApiKey];
            var env = config[PluginEnvinronment];
            var logLevel = config[DataDogLogLevel];

            Log.Logger = new LoggerConfiguration()
                .WriteTo.DatadogLogs(
                    apiKey: key,
                    source: env,
                    service: "service_name",
                    host: Dns.GetHostName(),
                    tags: new[] { config[PluginEnvinronment] },
                    logLevel: (LogEventLevel)Enum.Parse(enumType: typeof(LogEventLevel), value: logLevel, ignoreCase: true))
                .CreateLogger();
```

Log something:

```
Log.Error("Plugin config - {@config}", config);
```

Solution like this perfectly work with net core, but not in 4.5.2.
Lib version:
`Serilog.Sinks.Datadog.Logs.0.2.0`

**Comment by gtrak** [comment] 2019-02-14 22:55
I'm having the same issue, silent failure in 4.5.2.  We wanted to get datadog-logging working before porting the app to .Net Core.  Is there a possible workaround using another sink or Http API?

**Comment by gtrak** [comment] 2019-02-15 21:42
After trying to do this from scratch via the serilog network sink, it seems I can make normal TCP work, but not TLS.  I wonder if this is the root cause? 

https://medium.com/@kyle.gagnet/your-net-code-could-stop-working-in-june-afb35fbf29ca

**Comment by gtrak** [comment] 2019-02-15 22:16
yeap..  I already had the workaround from a zendesk API issue, but apparently that wasn't enough for datadog or my custom thing:
https://github.com/mozts2005/ZendeskApi_v2/issues/339#issuecomment-398694599

Upgrading the compile framework version to 4.6.1 and in webconfig runtime made both the custom thing I did over serilog.sinks.network and this sink work.

**Comment by jpoiron** [comment] 2019-02-28 19:09
We ran into this too with our .NET API and fixed it by setting `<httpRuntime targetFramework="4.6" />` in the web.config. Previously we had it set to 4.5. The difference appears to be the default TLS settings. In 4.6 it defaults to TLS 1.2 whereas in 4.5 it was TLS 1. The datadog intake endpoint seems to only support 1.2.

**Comment by NBParis** [comment] 2019-03-22 09:56
Hello,

Sorry for the delay and thanks a lot @jpoiron for the provided explanations.
This is indeed exactly the situation. 
The Datadog TCP intake only supports TLS 1.2 and we are working on adding a HTTPS forwarder option on the sink in addition of an update of the documentation to better highlight what was raised in this thread.

I'll go ahead and close this issue but feel free to reach out to support@datadoghq.com if you have any questions or issues.

**Closed by NBParis** 2019-03-22 09:56 UTC
