### ISSUE TITLE
Log messages are lost when remote server disconnects

### ISSUE THREAD

**Issue by lokalan** [DataDog/serilog-sinks-datadog-logs#21] opened 2019-01-24 20:05 UTC
The easiest way to reproduce this issue is to send 1 log message, then wait for 1 minute.  After 1 minute, the remote Datadog log intake server will send a `FIN` TCP packet, indicating it's closing the connection.

Now if you try to send more messages after this, some of them will be lost until `TcpClient` throws a `Broken Pipe` exception and we recreate the connection from the code to fix this issue: https://github.com/DataDog/serilog-sinks-datadog-logs/issues/8

It's the exact scenario described here: https://stackoverflow.com/questions/9683074/net-socket-doesnt-respond-to-remote-disconnect

I tried a few ways to detect the dropped connection and the only way that works is described in this article: https://stackoverflow.com/questions/1387459/how-to-check-if-tcpclient-connection-is-closed

I have a PR that fixes this issue: https://github.com/DataDog/serilog-sinks-datadog-logs/pull/20

**Comment by NBParis** [comment] 2019-02-05 12:22
Hello @lokalan ,

Thanks for the report and for helping to improve the sink.
I believe that @achntrl provided some feedback regarding your Pull request.

For very sparse logs, we realised that the best option might simply to leverage HTTP to send the logs rather than a stale long-lived TCP connection.

If you believe that would work in your case, I have attached the corresponding Pull request: https://github.com/DataDog/serilog-sinks-datadog-logs/pull/24

**Comment by lokalan** [comment] 2019-02-13 19:21
I think the HTTP client will work in our case.

I also noticed https://github.com/DataDog/serilog-sinks-datadog-logs/pull/26/files, I'd be curious if that fixed the issue for you?

I originally tried `TcpClient.Connected` but it would still return true even if the connection was really disconnected and the message lost, hence why I went with the `TcpConnectionInformation` approach.

**Comment by NBParis** [comment] 2019-04-12 12:17
Hello @lokalan ,

Just wanted to let you know that the package has been updated and that you can now use HTTPS forwarding.

This is actually the default behaviour now and this can still be overridden to go back to TCP by specifying `useTCP: true`.
The read me is also updated to reflect this change.

Let us know if that do work properly for you (I'll go ahead and close this issue but feel free to re-open it if you have any problem with the sink).

**Closed by NBParis** 2019-04-12 12:17 UTC

**Comment by minato128** [comment] 2019-08-08 13:58
The same problem occurred in my environment. I understood the cause. Thanks.
